#[unsafe(no_mangle)]
pub static mut vp8_block2left: [::core::ffi::c_uchar; 25] = [
    0 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    4 as i32 as ::core::ffi::c_uchar,
    4 as i32 as ::core::ffi::c_uchar,
    5 as i32 as ::core::ffi::c_uchar,
    5 as i32 as ::core::ffi::c_uchar,
    6 as i32 as ::core::ffi::c_uchar,
    6 as i32 as ::core::ffi::c_uchar,
    7 as i32 as ::core::ffi::c_uchar,
    7 as i32 as ::core::ffi::c_uchar,
    8 as i32 as ::core::ffi::c_uchar,
];
#[unsafe(no_mangle)]
pub static mut vp8_block2above: [::core::ffi::c_uchar; 25] = [
    0 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    0 as i32 as ::core::ffi::c_uchar,
    1 as i32 as ::core::ffi::c_uchar,
    2 as i32 as ::core::ffi::c_uchar,
    3 as i32 as ::core::ffi::c_uchar,
    4 as i32 as ::core::ffi::c_uchar,
    5 as i32 as ::core::ffi::c_uchar,
    4 as i32 as ::core::ffi::c_uchar,
    5 as i32 as ::core::ffi::c_uchar,
    6 as i32 as ::core::ffi::c_uchar,
    7 as i32 as ::core::ffi::c_uchar,
    6 as i32 as ::core::ffi::c_uchar,
    7 as i32 as ::core::ffi::c_uchar,
    8 as i32 as ::core::ffi::c_uchar,
];
